// inventory-frontend/src/pages/Auth/Login.tsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { Eye, EyeOff, Boxes, Lock, User } from 'lucide-react'
import { useMutation } from '@tanstack/react-query'
import { authApi } from '../../api/services'
import { useAuthStore, useToastStore } from '../../store'
import './Login.css'

export default function Login() {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const { setAuth } = useAuthStore()
  const { addToast } = useToastStore()

  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [showPassword, setShowPassword] = useState(false)

  const loginMutation = useMutation({
    mutationFn: () => authApi.login({ username, password }),
    onSuccess: (res) => {
      const { data } = res.data
      setAuth(data.token, data.refreshToken, data.user)
      localStorage.setItem('token', data.token)
      addToast('success', `Welcome back, ${data.user.firstName || data.user.username}!`)
      navigate('/')
    },
    onError: (err: any) => {
      const msg = err?.response?.data?.message || t('invalidCredentials')
      addToast('error', msg)
    }
  })

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!username.trim() || !password.trim()) return
    loginMutation.mutate()
  }

  return (
    <div className="login-page">
      {/* Animated background */}
      <div className="login-bg">
        <div className="login-bg-orb orb-1" />
        <div className="login-bg-orb orb-2" />
        <div className="login-bg-orb orb-3" />
      </div>

      {/* Login Card */}
      <div className="login-card">
        {/* Logo */}
        <div className="login-logo">
          <div className="login-logo-icon">
            <Boxes size={28} />
          </div>
          <div>
            <h2 className="login-logo-name">InvManager</h2>
            <p className="login-logo-sub">Inventory Management System</p>
          </div>
        </div>

        {/* Title */}
        <div className="login-header">
          <h1 className="login-title">{t('loginTitle')}</h1>
          <p className="login-subtitle">{t('loginSubtitle')}</p>
        </div>

        {/* Form */}
        <form className="login-form" onSubmit={handleSubmit} autoComplete="on">
          <div className="form-group">
            <label className="form-label">{t('username')}</label>
            <div className="input-wrapper">
              <span className="input-icon"><User size={16} /></span>
              <input
                type="text"
                className="form-input with-icon"
                placeholder={t('username')}
                value={username}
                onChange={e => setUsername(e.target.value)}
                autoComplete="username"
                required
              />
            </div>
          </div>

          <div className="form-group">
            <label className="form-label">{t('password')}</label>
            <div className="input-wrapper">
              <span className="input-icon"><Lock size={16} /></span>
              <input
                type={showPassword ? 'text' : 'password'}
                className="form-input with-icon with-icon-right"
                placeholder={t('password')}
                value={password}
                onChange={e => setPassword(e.target.value)}
                autoComplete="current-password"
                required
              />
              <button
                type="button"
                className="input-icon-right"
                onClick={() => setShowPassword(!showPassword)}
                tabIndex={-1}
              >
                {showPassword ? <EyeOff size={16} /> : <Eye size={16} />}
              </button>
            </div>
          </div>

          <button
            type="submit"
            className="btn btn-primary btn-lg w-full"
            disabled={loginMutation.isPending}
          >
            {loginMutation.isPending ? (
              <>
                <span className="spinner" />
                {t('loggingIn')}
              </>
            ) : t('loginBtn')}
          </button>
        </form>

        {/* Footer */}
        <p className="login-footer">
          © {new Date().getFullYear()} InvManager · All rights reserved
        </p>
      </div>
    </div>
  )
}

// inventory-frontend/src/app/features/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';
import { LucideAngularModule, Package, User, Lock, ArrowRight } from 'lucide-angular';

@Component({
  selector: 'app-login',
  imports: [CommonModule, FormsModule, LucideAngularModule],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css'
})
export class LoginComponent {
  credentials = {
    username: '',
    password: ''
  };
  error: string = '';
  isLoading: boolean = false;
  showPassword = false;

  constructor(private authService: AuthService, private router: Router) {}

  togglePassword() {
    this.showPassword = !this.showPassword;
  }

  onSubmit() {
    this.error = '';
    
    if (!this.credentials.username || !this.credentials.password) {
      this.error = 'Please enter both username and password';
      return;
    }

    this.isLoading = true;
    this.authService.login(this.credentials).subscribe({
      next: (res) => {
        this.isLoading = false;
        this.router.navigate(['/']);
      },
      error: (err) => {
        this.isLoading = false;
        this.error = err.error?.message || 'Invalid credentials or server error';
      }
    });
  }
}

<div class="login-page">
  <!-- Animated background -->
  <div class="login-bg">
    <div class="login-bg-orb orb-1"></div>
    <div class="login-bg-orb orb-2"></div>
    <div class="login-bg-orb orb-3"></div>
  </div>

  <!-- Login Card -->
  <div class="login-card">
    <!-- Logo -->
    <div class="login-logo">
      <div class="login-logo-icon">
        <lucide-icon name="boxes" [size]="28"></lucide-icon>
      </div>
      <div>
        <h2 class="login-logo-name">InvManager</h2>
        <p class="login-logo-sub">Inventory Management System</p>
      </div>
    </div>

    <!-- Title -->
    <div class="login-header">
      <h1 class="login-title">Welcome Back!</h1>
      <p class="login-subtitle">Sign in to manage your inventory</p>
    </div>

    <!-- Error Message -->
    <div *ngIf="error" class="error-message" style="margin-bottom: 1rem; color: #ef4444; background: rgba(239, 68, 68, 0.12); padding: 10px; border-radius: 6px; text-align: center; font-size: 14px;">
      {{ error }}
    </div>

    <!-- Form -->
    <form class="login-form" (ngSubmit)="onSubmit()" autocomplete="on">
      <div class="form-group">
        <label class="form-label">Username</label>
        <div class="input-wrapper">
          <span class="input-icon"><lucide-icon name="user" [size]="16"></lucide-icon></span>
          <input
            type="text"
            class="form-input with-icon"
            placeholder="Username"
            name="username"
            [(ngModel)]="credentials.username"
            autocomplete="username"
            required
          />
        </div>
      </div>

      <div class="form-group">
        <label class="form-label">Password</label>
        <div class="input-wrapper">
          <span class="input-icon"><lucide-icon name="lock" [size]="16"></lucide-icon></span>
          <input
            [type]="showPassword ? 'text' : 'password'"
            class="form-input with-icon with-icon-right"
            placeholder="Password"
            name="password"
            [(ngModel)]="credentials.password"
            autocomplete="current-password"
            required
          />
          <button
            type="button"
            class="input-icon-right"
            style="background: transparent; border: none; cursor: pointer; color: var(--text-muted);"
            (click)="togglePassword()"
            tabindex="-1"
          >
            <lucide-icon *ngIf="showPassword" name="eye-off" [size]="16"></lucide-icon>
            <lucide-icon *ngIf="!showPassword" name="eye" [size]="16"></lucide-icon>
          </button>
        </div>
      </div>

      <button
        type="submit"
        class="btn btn-primary btn-lg w-full"
        [disabled]="isLoading"
      >
        <ng-container *ngIf="isLoading">
          <span class="spinner"></span>
          Logging In...
        </ng-container>
        <ng-container *ngIf="!isLoading">
          Sign In
        </ng-container>
      </button>
    </form>

    <!-- Footer -->
    <p class="login-footer">
      © 2026 InvManager · All rights reserved
    </p>
  </div>
</div>
