// inventory-frontend/src/app/features/users/users.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { LucideAngularModule, Search, Users, Shield, User, UserCheck, UserX, Trash2, Plus } from 'lucide-angular';
import { UserService } from '../../core/services/user.service';
import { AuthService } from '../../core/services/auth.service';
import { TranslatePipe } from '@ngx-translate/core';

@Component({
  selector: 'app-users',
  imports: [CommonModule, FormsModule, LucideAngularModule, TranslatePipe],
  templateUrl: './users.component.html',
  styleUrl: './users.component.css'
})
export class UsersComponent implements OnInit {
  readonly icons = { Search, Users, Shield, User, UserCheck, UserX, Trash2, Plus };

  users: any[] = [];
  totalCount = 0;
  totalPages = 1;
  page = 1;
  searchQuery = '';
  isLoading = false;

  deleteConfirm: any = null;
  isDeleting = false;

  // Registration Modal
  showRegisterModal = false;
  isRegistering = false;
  registerError = '';
  newUser = {
    username: '',
    email: '',
    password: '',
    firstName: '',
    lastName: '',
    role: 'Employee'
  };

  currentUser: any;

  constructor(
    private userService: UserService,
    private authService: AuthService
  ) {
    this.currentUser = this.authService.getCurrentUser();
  }

  ngOnInit() {
    this.loadUsers();
  }

  get currentUserId() {
    return this.currentUser?.['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier'];
  }

  loadUsers() {
    this.isLoading = true;
    this.userService.getUsers(this.page, 15, this.searchQuery).subscribe({
      next: (res) => {
        this.users = res.data?.items || [];
        this.totalCount = res.data?.totalCount || 0;
        this.totalPages = res.data?.totalPages || 1;
        this.isLoading = false;
      },
      error: () => this.isLoading = false
    });
  }

  onSearch() {
    this.page = 1;
    this.loadUsers();
  }

  prevPage() {
    if (this.page > 1) {
      this.page--;
      this.loadUsers();
    }
  }

  nextPage() {
    if (this.page < this.totalPages) {
      this.page++;
      this.loadUsers();
    }
  }

  toggleStatus(user: any) {
    this.userService.toggleStatus(user.id).subscribe(() => {
      this.loadUsers();
    });
  }

  confirmDelete(user: any) {
    this.deleteConfirm = user;
  }

  deleteUser() {
    if (!this.deleteConfirm) return;
    this.isDeleting = true;
    this.userService.deleteUser(this.deleteConfirm.id).subscribe({
      next: () => {
        this.isDeleting = false;
        this.deleteConfirm = null;
        this.loadUsers();
      },
      error: () => this.isDeleting = false
    });
  }

  openRegister() {
    this.registerError = '';
    this.newUser = { username: '', email: '', password: '', firstName: '', lastName: '', role: 'Employee' };
    this.showRegisterModal = true;
  }

  registerUser() {
    this.isRegistering = true;
    this.registerError = '';
    this.authService.register(this.newUser).subscribe({
      next: () => {
        this.isRegistering = false;
        this.showRegisterModal = false;
        this.loadUsers();
      },
      error: (err) => {
        this.isRegistering = false;
        this.registerError = err.error?.message || 'Failed to register user. Check validation rules.';
      }
    });
  }
}

<div style="display: flex; flex-direction: column; gap: 20px;">
  
  <div class="page-header">
    <div>
      <h1 class="page-title">{{ 'SIDEBAR.USERS' | translate }}</h1>
      <p class="page-subtitle">{{ 'USERS.SUBTITLE' | translate }}</p>
    </div>
    <button class="btn btn-primary" (click)="openRegister()">
      <lucide-icon [img]="icons.Plus" [size]="16"></lucide-icon>
      {{ 'USERS.REGISTER_USER' | translate }}
    </button>
  </div>

  <div class="card" style="padding: 12px 16px;">
    <div class="search-filter-row">
      
      <div class="search-wrapper" style="min-width: 220px; flex: 1; max-width: 320px;">
        <span class="search-icon"><lucide-icon [img]="icons.Search" [size]="16"></lucide-icon></span>
        <input 
          class="search-input" 
          [placeholder]="'COMMON.SEARCH' | translate"
          [(ngModel)]="searchQuery" 
          (ngModelChange)="onFilterChange()" 
        />
      </div>

      <div class="search-filter-controls">
        
        <select class="form-select filter-select" style="width: 160px;" [(ngModel)]="selectedRole" (ngModelChange)="onFilterChange()">
          <option value="">{{ 'USERS.ROLE' | translate }} ({{ 'COMMON.ALL' | translate }})</option>
          <option value="SuperAdmin">Super Admin</option>
          <option value="InventoryManager">Inventory Manager</option>
          <option value="WarehouseStaff">Warehouse Staff</option>
          <option value="PurchasingOfficer">Purchasing Officer</option>
          <option value="Sales">Sales</option>
          <option value="Accountant">Accountant</option>
          <option value="Auditor">Auditor</option>
        </select>

        <select class="form-select filter-select" style="width: 160px;" [(ngModel)]="selectedStatus" (ngModelChange)="onFilterChange()">
          <option value="">{{ 'COMMON.STATUS' | translate }} ({{ 'COMMON.ALL' | translate }})</option>
          <option value="active">{{ 'COMMON.ACTIVE' | translate }}</option>
          <option value="inactive">{{ 'COMMON.INACTIVE' | translate }}</option>
        </select>

        <button class="btn btn-excel btn-sm" (click)="exportToExcel()" [disabled]="isLoading || getFilteredUsers().length === 0">
          Excel
        </button>
        <button class="btn btn-pdf btn-sm" (click)="exportToPdf()" [disabled]="isLoading || getFilteredUsers().length === 0">
          PDF
        </button>
      </div>
    </div>
  </div>

  <div class="card" style="padding: 0;">
    <div class="table-wrapper">
      <table id="users-table">
        <thead>
          <tr>
            <th>{{ 'COMMON.ID' | translate }}</th>
            <th>{{ 'USERS.USERNAME' | translate }}</th>
            <th>{{ 'COMMON.EMAIL' | translate }}</th>
            <th>{{ 'USERS.ROLE' | translate }}</th>
            <th>{{ 'COMMON.STATUS' | translate }}</th>
            <th>{{ 'USERS.JOINED' | translate }}</th>
            <th style="text-align: right;">{{ 'COMMON.ACTIONS' | translate }}</th>
          </tr>
        </thead>
        <tbody>
          
          <ng-container *ngIf="isLoading">
            <tr *ngFor="let dummy of [1,2,3,4,5]">
              <td *ngFor="let col of [1,2,3,4,5,6,7]">
                <div class="skeleton" style="height: 16px; width: 70%;"></div>
              </td>
            </tr>
          </ng-container>
          
          <tr *ngIf="!isLoading && getFilteredUsers().length === 0">
            <td colspan="7">
              <app-empty-state [title]="'USERS.NO_USERS' | translate">
                <lucide-icon [img]="icons.Users" [size]="40"></lucide-icon>
              </app-empty-state>
            </td>
          </tr>
          
          <ng-container *ngIf="!isLoading && getFilteredUsers().length > 0">
            <tr *ngFor="let u of getFilteredUsers()">
              <td [attr.data-label]="'COMMON.ID' | translate" style="font-weight: bold; color: var(--text-muted);">#{{ u.id }}</td>
              <td [attr.data-label]="'USERS.USERNAME' | translate">
                <div style="display:flex;align-items:center;gap:10px;">
                  <div class="avatar relative group cursor-pointer" style="overflow: hidden;">
                    <img *ngIf="u.profilePicture" [src]="u.profilePicture" class="w-full h-full object-cover" />
                    <span *ngIf="!u.profilePicture">{{ u.firstName?.charAt(0) || u.username?.charAt(0) || 'U' }}</span>
                  </div>
                  <div>
                    <div class="font-bold">{{ u.username }}</div>
                    <div class="text-xs text-muted">{{ u.firstName }} {{ u.lastName }}</div>
                  </div>
                </div>
              </td>
              <td [attr.data-label]="'COMMON.EMAIL' | translate">{{ u.email || '—' }}</td>
              <td [attr.data-label]="'USERS.ROLE' | translate">
                <span class="badge" [ngClass]="u.role === 'SuperAdmin' ? 'badge-accent' : 'badge-info'">
                  {{ u.role }}
                </span>
              </td>
              <td [attr.data-label]="'COMMON.STATUS' | translate">
                <span class="badge" [ngClass]="u.isActive ? 'badge-success' : 'badge-danger'">
                  {{ (u.isActive ? 'COMMON.ACTIVE' : 'COMMON.INACTIVE') | translate }}
                </span>
              </td>
              <td [attr.data-label]="'USERS.JOINED' | translate" style="font-size:12px;color:var(--text-secondary);">{{ u.createdAt | date:'mediumDate' }}</td>
              <td [attr.data-label]="'COMMON.ACTIONS' | translate">
                <div style="display:flex;gap:6px;justify-content:flex-end;align-items:center;">

                  <button class="btn btn-sm btn-ghost user-action-btn" (click)="openView(u)" title="View Details">
                    <lucide-icon [img]="icons.Eye" [size]="13"></lucide-icon>
                  </button>
                  
                  <button class="btn btn-sm btn-secondary user-action-btn" (click)="openEdit(u)" title="Edit Details">
                    <lucide-icon [img]="icons.Pencil" [size]="13"></lucide-icon>
                  </button>
                  
                  <button class="btn btn-sm user-action-btn" [ngClass]="u.isActive ? 'btn-ghost' : 'btn-secondary'"
                    (click)="toggleStatus(u)" [title]="'USERS.TOGGLE_STATUS' | translate">
                    <lucide-icon [img]="u.isActive ? icons.UserX : icons.UserCheck" [size]="13"></lucide-icon>
                  </button>
                  
                  <button *ngIf="u.id.toString() !== currentUserId"
                    class="btn btn-danger btn-icon btn-sm user-action-btn"
                    (click)="confirmDelete(u)" [title]="'USERS.DELETE_USER' | translate">
                    <lucide-icon [img]="icons.Trash2" [size]="13"></lucide-icon>
                  </button>
                </div>
              </td>
            </tr>
          </ng-container>
        </tbody>
      </table>
    </div>

    <div class="pagination" *ngIf="totalPages > 0" style="display: flex; justify-content: space-between; align-items: center; width: 100%; padding: 16px 24px;">
      <div style="display: flex; align-items: center; gap: 12px;">
        <span class="pagination-info" style="margin: 0;">{{ 'PRODUCTS.PAGE' | translate }} {{ page }} / {{ totalPages }}</span>
        <select class="form-select" style="width: auto; padding: 4px 30px 4px 10px; font-size: 13px;" [(ngModel)]="pageSize" (ngModelChange)="onPageSizeChange()">
          <option [value]="5">5</option>
          <option [value]="10">10</option>
          <option [value]="15">15</option>
          <option [value]="25">25</option>
          <option [value]="50">50</option>
          <option [value]="100">100</option>
        </select>
      </div>
      <div class="pagination-controls">
        <button class="page-btn" [disabled]="page === 1" (click)="prevPage()">
          <lucide-icon [img]="icons.ChevronLeft" [size]="14"></lucide-icon>
        </button>
        <button *ngFor="let pg of getPagesArray()" class="page-btn" [ngClass]="{ active: page === pg }" (click)="goToPage(pg)">
          {{ pg }}
        </button>
        <button class="page-btn" [disabled]="page === totalPages" (click)="nextPage()">
          <lucide-icon [img]="icons.ChevronRight" [size]="14"></lucide-icon>
        </button>
      </div>
    </div>
  </div>

  <div class="custom-modal-overlay" *ngIf="viewUser" (click)="closeView()">
    <div class="custom-modal view-modal" (click)="$event.stopPropagation()">
      <div class="custom-modal-header">
        <h3 class="custom-modal-title">User Details</h3>
        <button class="btn btn-ghost btn-sm btn-icon" (click)="closeView()">
          <lucide-icon [img]="icons.X" [size]="16"></lucide-icon>
        </button>
      </div>
      <div class="custom-modal-body" style="padding-top:16px;">
        
        <div class="view-hero">
          <div class="avatar view-avatar">{{ viewUser?.firstName?.charAt(0) || viewUser?.username?.charAt(0) || 'U' }}</div>
          <div>
            <div style="font-size:18px;font-weight:700;">{{ viewUser?.firstName }} {{ viewUser?.lastName }}</div>
            <div style="font-size:13px;color:var(--text-muted);">&#64;{{ viewUser?.username }}</div>
            <span class="badge" style="margin-top:6px;" [ngClass]="viewUser?.role === 'SuperAdmin' ? 'badge-accent' : 'badge-info'">
              {{ viewUser?.role }}
            </span>
          </div>
        </div>
        
        <div class="view-grid">
          <div class="view-field">
            <span class="view-field-label">{{ 'COMMON.EMAIL' | translate }}</span>
            <span class="view-field-value">{{ viewUser?.email || '—' }}</span>
          </div>
          <div class="view-field">
            <span class="view-field-label">{{ 'COMMON.STATUS' | translate }}</span>
            <span class="badge" [ngClass]="viewUser?.isActive ? 'badge-success' : 'badge-danger'">
              {{ (viewUser?.isActive ? 'COMMON.ACTIVE' : 'COMMON.INACTIVE') | translate }}
            </span>
          </div>
          <div class="view-field">
            <span class="view-field-label">{{ 'USERS.JOINED' | translate }}</span>
            <span class="view-field-value">{{ viewUser?.createdAt | date:'longDate' }}</span>
          </div>
          <div class="view-field">
            <span class="view-field-label">{{ 'USERS.ROLE' | translate }}</span>
            <span class="view-field-value">{{ viewUser?.role }}</span>
          </div>
        </div>
      </div>
      <div class="custom-modal-footer">
        <button class="btn btn-ghost" (click)="closeView()">{{ 'COMMON.CANCEL' | translate }}</button>
        <button class="btn btn-secondary" (click)="closeView(); openEdit(viewUser)">
          <lucide-icon [img]="icons.Pencil" [size]="14"></lucide-icon>
          {{ 'COMMON.EDIT' | translate }}
        </button>
      </div>
    </div>
  </div>

  <div class="custom-modal-overlay" *ngIf="editUser" (click)="closeEdit()">
    <div class="custom-modal" style="max-width:500px;" (click)="$event.stopPropagation()">
      <div class="custom-modal-header">
        <h3 class="custom-modal-title">
          <lucide-icon [img]="icons.Pencil" [size]="18" style="color:var(--accent);margin-right:8px;"></lucide-icon>
          {{ 'COMMON.EDIT' | translate }}: {{ editUser?.username }}
        </h3>
        <button class="btn btn-ghost btn-sm btn-icon" (click)="closeEdit()">
          <lucide-icon [img]="icons.X" [size]="16"></lucide-icon>
        </button>
      </div>
      <div class="custom-modal-body" style="display:flex;flex-direction:column;gap:14px;padding-top:16px;">
          <div style="display: flex; align-items: center; gap: 16px; margin-bottom: 8px;">
            <div class="avatar relative" style="overflow: hidden; width: 64px; height: 64px; border-radius: 50%; display: flex; align-items: center; justify-content: center; background: var(--bg-secondary); border: 2px solid var(--border);">
              <img *ngIf="editUser?.profilePicture" [src]="editUser?.profilePicture" style="width: 100%; height: 100%; object-fit: cover;" />
              <span *ngIf="!editUser?.profilePicture" style="font-size: 24px; font-weight: bold; color: var(--text-secondary);">{{ editUser?.firstName?.charAt(0) || editUser?.username?.charAt(0) || 'U' }}</span>
            </div>
            <div style="display: flex; flex-direction: column; gap: 6px;">
              <button class="btn btn-sm btn-secondary" (click)="openProfilePictureModal(editUser)" style="display: flex; align-items: center; gap: 6px;">
                <lucide-icon [img]="icons.UploadCloud" [size]="14"></lucide-icon> Upload Picture
              </button>
              <button *ngIf="editUser?.profilePicture" class="btn btn-sm btn-ghost text-error" (click)="deleteProfilePicture(editUser)" style="display: flex; align-items: center; gap: 6px; padding: 0 10px;">
                <lucide-icon [img]="icons.Trash2" [size]="14"></lucide-icon> Remove Picture
              </button>
            </div>
          </div>
          <div class="badge badge-success" *ngIf="editSuccess" style="padding:10px;border-radius:8px;font-size:13px;">
          {{ editSuccess }}
        </div>
        <div class="badge badge-danger" *ngIf="editError" style="padding:10px;border-radius:8px;font-size:13px;">
          {{ editError }}
        </div>

        <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;">
          <div class="form-group">
            <label class="form-label">{{ 'USERS.FIRST_NAME' | translate }}</label>
            <input class="form-input" [(ngModel)]="editForm.firstName" />
          </div>
          <div class="form-group">
            <label class="form-label">{{ 'USERS.LAST_NAME' | translate }}</label>
            <input class="form-input" [(ngModel)]="editForm.lastName" />
          </div>
        </div>

        <div class="form-group">
          <label class="form-label">{{ 'COMMON.EMAIL' | translate }} *</label>
          <input type="email" class="form-input" [(ngModel)]="editForm.email" />
        </div>

        <div class="form-group">
          <label class="form-label">{{ 'USERS.ROLE' | translate }}</label>
          <select class="form-select" [(ngModel)]="editForm.role">
            <option value="SuperAdmin">Super Admin</option>
            <option value="InventoryManager">Inventory Manager</option>
            <option value="WarehouseStaff">Warehouse Staff</option>
            <option value="PurchasingOfficer">Purchasing Officer</option>
            <option value="Sales">Sales</option>
            <option value="Accountant">Accountant</option>
            <option value="Auditor">Auditor</option>
          </select>
        </div>
      </div>
      <div class="custom-modal-footer">
        <button class="btn btn-ghost" (click)="closeEdit()">{{ 'COMMON.CANCEL' | translate }}</button>
        <button class="btn btn-primary" (click)="saveEdit()" [disabled]="isSavingEdit">
          <app-spinner *ngIf="isSavingEdit" padding="0"></app-spinner>
          <lucide-icon [img]="icons.Save" [size]="14" *ngIf="!isSavingEdit"></lucide-icon>
          {{ 'COMMON.SAVE' | translate }}
        </button>
      </div>
    </div>
  </div>

  <div class="custom-modal-overlay" *ngIf="deleteConfirm" (click)="deleteConfirm = null">
    <div class="custom-modal" style="max-width:400px;" (click)="$event.stopPropagation()">
      <div class="custom-modal-header">
        <h3 class="custom-modal-title" style="color:var(--danger);">{{ 'USERS.DELETE_USER' | translate }}</h3>
      </div>
      <div class="custom-modal-body" style="padding-top:16px;">
        <p style="color:var(--text-secondary);font-size:14px;">
          {{ 'USERS.DELETE_USER_MSG' | translate:{username: deleteConfirm.username} }}
        </p>
      </div>
      <div class="custom-modal-footer">
        <button class="btn btn-ghost" (click)="deleteConfirm = null">{{ 'COMMON.CANCEL' | translate }}</button>
        <button class="btn btn-danger" (click)="deleteUser()" [disabled]="isDeleting">
          <app-spinner *ngIf="isDeleting" padding="0"></app-spinner>
          <lucide-icon [img]="icons.Trash2" [size]="14" *ngIf="!isDeleting"></lucide-icon>
          {{ 'COMMON.DELETE' | translate }}
        </button>
      </div>
    </div>
  </div>

  <div class="custom-modal-overlay" *ngIf="showRegisterModal" (click)="showRegisterModal = false">
    <div class="custom-modal" style="max-width:500px;" (click)="$event.stopPropagation()">
      <div class="custom-modal-header">
        <h3 class="custom-modal-title">{{ 'USERS.REGISTER_NEW_USER' | translate }}</h3>
        <button class="btn btn-ghost btn-sm btn-icon" (click)="showRegisterModal = false">
          <lucide-icon [img]="icons.X" [size]="16"></lucide-icon>
        </button>
      </div>
      <div class="custom-modal-body" style="display:flex;flex-direction:column;gap:14px;padding-top:16px;">
        <div class="badge badge-danger" *ngIf="registerError" style="padding:10px;border-radius:8px;font-size:13px;">
          {{ registerError }}
        </div>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;">
          <div class="form-group">
            <label class="form-label">{{ 'USERS.FIRST_NAME' | translate }}</label>
            <input class="form-input" [(ngModel)]="newUser.firstName" />
          </div>
          <div class="form-group">
            <label class="form-label">{{ 'USERS.LAST_NAME' | translate }}</label>
            <input class="form-input" [(ngModel)]="newUser.lastName" />
          </div>
        </div>
        <div class="form-group">
          <label class="form-label">{{ 'USERS.USERNAME' | translate }} *</label>
          <input class="form-input" [(ngModel)]="newUser.username" />
        </div>
        <div class="form-group">
          <label class="form-label">{{ 'COMMON.EMAIL' | translate }} *</label>
          <input type="email" class="form-input" [(ngModel)]="newUser.email" />
        </div>
        <div class="form-group">
          <label class="form-label">{{ 'USERS.PASSWORD' | translate }} *</label>
          <input type="password" class="form-input" [(ngModel)]="newUser.password" />
        </div>
        <div class="form-group">
          <label class="form-label">{{ 'USERS.ROLE' | translate }} *</label>
          <select class="form-select" [(ngModel)]="newUser.role">
            <option value="SuperAdmin">Super Admin</option>
            <option value="InventoryManager">Inventory Manager</option>
            <option value="WarehouseStaff">Warehouse Staff</option>
            <option value="PurchasingOfficer">Purchasing Officer</option>
            <option value="Sales">Sales</option>
            <option value="Accountant">Accountant</option>
            <option value="Auditor">Auditor</option>
          </select>
        </div>
      </div>
      <div class="custom-modal-footer">
        <button class="btn btn-ghost" (click)="showRegisterModal = false">{{ 'COMMON.CANCEL' | translate }}</button>
        <button class="btn btn-primary" (click)="registerUser()"
          [disabled]="!newUser.username || !newUser.email || !newUser.password || isRegistering">
          <app-spinner *ngIf="isRegistering" padding="0"></app-spinner>
          {{ 'USERS.REGISTER_USER' | translate }}
        </button>
      </div>
    </div>
  </div>

</div>

// inventory-frontend/src/pages/Users/Users.tsx
import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useTranslation } from 'react-i18next'
import { Search, UserCheck, UserX, Trash2, Users, Shield, User } from 'lucide-react'
import { usersApi } from '../../api/services'
import { useToastStore } from '../../store'
import { format } from 'date-fns'

export default function UsersPage() {
  const { t } = useTranslation()
  const { addToast } = useToastStore()
  const qc = useQueryClient()

  const [search, setSearch] = useState('')
  const [page, setPage] = useState(1)
  const [deleteConfirm, setDeleteConfirm] = useState<any>(null)

  const { data, isLoading } = useQuery({
    queryKey: ['users', page, search],
    queryFn: () => usersApi.getAll({ page, pageSize: 15, search: search || undefined })
  })

  const result = data?.data?.data
  const users = result?.items || []
  const totalPages = result?.totalPages || 1

  const toggleMutation = useMutation({
    mutationFn: (id: number) => usersApi.toggleStatus(id),
    onSuccess: () => { addToast('success', 'User status updated'); qc.invalidateQueries({ queryKey: ['users'] }) },
    onError: () => addToast('error', 'Failed to update user status')
  })

  const deleteMutation = useMutation({
    mutationFn: (id: number) => usersApi.delete(id),
    onSuccess: () => { addToast('success', 'User deleted'); setDeleteConfirm(null); qc.invalidateQueries({ queryKey: ['users'] }) },
    onError: (err: any) => addToast('error', err?.response?.data?.message || 'Failed to delete user')
  })

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
      <div className="page-header">
        <div>
          <h1 className="page-title">{t('users')}</h1>
          <p className="page-subtitle">{result?.totalCount || 0} {t('items')}</p>
        </div>
      </div>

      <div className="card" style={{ padding: '14px 20px' }}>
        <div className="search-wrapper">
          <span className="search-icon"><Search size={16} /></span>
          <input
            className="search-input"
            placeholder={t('search')}
            value={search}
            onChange={e => { setSearch(e.target.value); setPage(1) }}
          />
        </div>
      </div>

      <div className="card" style={{ padding: 0 }}>
        <div className="table-wrapper">
          <table>
            <thead>
              <tr>
                <th>{t('username')}</th>
                <th>{t('email')}</th>
                <th>{t('role')}</th>
                <th>Status</th>
                <th>Joined</th>
                <th>{t('actions')}</th>
              </tr>
            </thead>
            <tbody>
              {isLoading
                ? Array.from({ length: 5 }).map((_, i) => (
                    <tr key={i}>
                      {Array.from({ length: 6 }).map((__, j) => (
                        <td key={j}><div className="skeleton" style={{ height: 16, width: '70%' }} /></td>
                      ))}
                    </tr>
                  ))
                : users.length === 0
                ? (
                    <tr><td colSpan={6}>
                      <div className="empty-state"><Users size={40} /><p>{t('noUsers')}</p></div>
                    </td></tr>
                  )
                : users.map((u: any) => (
                    <tr key={u.id}>
                      <td>
                        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                          <div className="avatar">
                            {u.firstName?.[0] || u.username?.[0] || 'U'}
                          </div>
                          <div>
                            <div style={{ fontWeight: 600 }}>{u.username}</div>
                            <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>
                              {u.firstName} {u.lastName}
                            </div>
                          </div>
                        </div>
                      </td>
                      <td style={{ fontSize: 13 }}>{u.email || '—'}</td>
                      <td>
                        <span className={`badge ${u.role === 'Manager' ? 'badge-accent' : 'badge-info'}`}
                          style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}>
                          {u.role === 'Manager' ? <Shield size={10} /> : <User size={10} />}
                          {u.role}
                        </span>
                      </td>
                      <td>
                        <span className={`badge ${u.isActive ? 'badge-success' : 'badge-danger'}`}>
                          {u.isActive ? t('active') : t('inactive')}
                        </span>
                      </td>
                      <td style={{ fontSize: 12, color: 'var(--text-muted)' }}>
                        {format(new Date(u.createdAt), 'dd MMM yyyy')}
                      </td>
                      <td>
                        <div style={{ display: 'flex', gap: 6 }}>
                          <button
                            className={`btn btn-sm ${u.isActive ? 'btn-ghost' : 'btn-secondary'}`}
                            onClick={() => toggleMutation.mutate(u.id)}
                            disabled={toggleMutation.isPending}
                            title={t('toggleStatus')}
                          >
                            {u.isActive ? <UserX size={13} /> : <UserCheck size={13} />}
                          </button>
                          {u.id !== 1 && (
                            <button
                              className="btn btn-danger btn-icon btn-sm"
                              onClick={() => setDeleteConfirm(u)}
                              title={t('delete')}
                            >
                              <Trash2 size={13} />
                            </button>
                          )}
                        </div>
                      </td>
                    </tr>
                  ))
              }
            </tbody>
          </table>
        </div>
        <div className="pagination">
          <span className="pagination-info">{t('page')} {page} {t('of')} {totalPages}</span>
          <div className="pagination-controls">
            <button className="page-btn" disabled={page === 1} onClick={() => setPage(p => p - 1)}>‹</button>
            <button className="page-btn" disabled={page === totalPages} onClick={() => setPage(p => p + 1)}>›</button>
          </div>
        </div>
      </div>

      {deleteConfirm && (
        <div className="modal-overlay" onClick={() => setDeleteConfirm(null)}>
          <div className="modal" style={{ maxWidth: 400 }} onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h3 className="modal-title" style={{ color: 'var(--danger)' }}>Delete User</h3>
            </div>
            <div className="modal-body">
              <p style={{ color: 'var(--text-secondary)', fontSize: 14 }}>
                Delete user <strong>"{deleteConfirm.username}"</strong>? This cannot be undone.
              </p>
            </div>
            <div className="modal-footer">
              <button className="btn btn-ghost" onClick={() => setDeleteConfirm(null)}>{t('cancel')}</button>
              <button
                className="btn btn-danger"
                onClick={() => deleteMutation.mutate(deleteConfirm.id)}
                disabled={deleteMutation.isPending}
              >
                {deleteMutation.isPending ? <span className="spinner" /> : <Trash2 size={14} />}
                {t('delete')}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
