// inventory-frontend/src/app/features/inventory/inventory.component.ts
import { Component, OnInit, ChangeDetectionStrategy, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { LucideAngularModule, Search, Download, Plus, ClipboardList, ChevronLeft, ChevronRight } from 'lucide-angular';
import { InventoryService } from '../../core/services/inventory.service';
import { ProductService } from '../../core/services/product.service';
import { AuthService } from '../../core/services/auth.service';
import { TranslatePipe } from '@ngx-translate/core';
import { ExportExcelService } from '../../core/services/export-excel.service';
import { ExportPdfService } from '../../core/services/export-pdf.service';

@Component({
  selector: 'app-inventory',
  imports: [CommonModule, FormsModule, LucideAngularModule, TranslatePipe],
  templateUrl: './inventory.component.html',
  styleUrl: './inventory.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class InventoryComponent implements OnInit {
  readonly icons = { Search, Download, Plus, ClipboardList, ChevronLeft, ChevronRight };

  logs: any[] = [];
  products: any[] = [];
  totalCount = 0;
  totalPages = 1;
  page = 1;
  pageSize = 15;
  actionFilter = '';
  searchQuery = '';
  isLoading = false;

  user: any;

  actionModal: 'add' | 'sell' | 'adjust' | 'return' | null = null;
  isSubmitting = false;
  actionError = '';

  selectedProductId: number | '' = '';
  quantity: number = 1;
  notes: string = '';

  constructor(
    private inventoryService: InventoryService,
    private productService: ProductService,
    private authService: AuthService,
    private exportExcel: ExportExcelService,
    private exportPdf: ExportPdfService,
    private cdr: ChangeDetectorRef
  ) {
    this.user = this.authService.getCurrentUser();
  }

  ngOnInit() {
    this.loadLogs();
    this.loadProducts();
  }

  get isAdmin() {
    return this.user?.['http://schemas.microsoft.com/ws/2008/06/identity/claims/role'] === 'Manager';
  }

  loadLogs() {
    this.isLoading = true;
    this.inventoryService.getInventoryLogs(this.page, this.pageSize, this.actionFilter, this.searchQuery).subscribe({
      next: (res) => {
        this.logs = res.data?.items || [];
        this.totalCount = res.data?.totalCount || 0;
        this.totalPages = res.data?.totalPages || 1;
        this.isLoading = false;
        this.cdr.markForCheck();
      },
      error: () => {
        this.isLoading = false;
        this.cdr.markForCheck();
      }
    });
  }

  getFilteredLogs() {
    return this.logs;
  }

  onFilterChange() {
    this.page = 1;
    this.loadLogs();
  }

  onPageSizeChange() {
    this.page = 1;
    this.loadLogs();
  }

  loadProducts() {
    
    this.productService.getProducts(1, 1000).subscribe(res => {
      this.products = res.data?.items || [];
      this.cdr.markForCheck();
    });
  }

  filterByAction(action: string) {
    this.actionFilter = action;
    this.page = 1;
    this.loadLogs();
  }

  prevPage() {
    if (this.page > 1) {
      this.page--;
      this.loadLogs();
    }
  }

  nextPage() {
    if (this.page < this.totalPages) {
      this.page++;
      this.loadLogs();
    }
  }

  goToPage(pg: number) {
    this.page = pg;
    this.loadLogs();
  }

  getPagesArray() {
    const pages = [];
    const maxPages = Math.min(this.totalPages, 5);
    for (let i = 1; i <= maxPages; i++) {
      pages.push(i);
    }
    return pages;
  }

  openActionModal(action: 'add' | 'sell' | 'adjust' | 'return') {
    this.actionModal = action;
    this.selectedProductId = '';
    this.quantity = action === 'adjust' ? 0 : 1;
    this.notes = '';
    this.actionError = '';
  }

  closeActionModal() {
    this.actionModal = null;
  }

  getModalTitle() {
    switch (this.actionModal) {
      case 'add': return 'INVENTORY.ADD_STOCK';
      case 'sell': return 'INVENTORY.SELL_STOCK';
      case 'adjust': return 'INVENTORY.ADJUST_STOCK';
      case 'return': return 'INVENTORY.RETURN_STOCK';
      default: return '';
    }
  }

  getQtyLabel() {
    switch (this.actionModal) {
      case 'add': return 'INVENTORY.QTY_TO_ADD';
      case 'sell': return 'INVENTORY.QTY_TO_SELL';
      case 'adjust': return 'INVENTORY.NEW_QTY';
      case 'return': return 'INVENTORY.QTY_TO_RETURN';
      default: return 'INVENTORY.QUANTITY_LABEL';
    }
  }

  submitAction() {
    if (!this.selectedProductId) return;
    
    this.isSubmitting = true;
    this.actionError = '';

    const payload = {
      productId: Number(this.selectedProductId),
      quantity: this.quantity,
      notes: this.notes
    };

    let actionObs;
    switch (this.actionModal) {
      case 'add': actionObs = this.inventoryService.addStock(payload); break;
      case 'sell': actionObs = this.inventoryService.sellStock(payload); break;
      case 'adjust': 
        actionObs = this.inventoryService.adjustStock({
          productId: payload.productId, 
          newQuantity: payload.quantity, 
          notes: payload.notes
        }); 
        break;
      case 'return': actionObs = this.inventoryService.returnStock(payload); break;
    }

    if (!actionObs) return;

    actionObs.subscribe({
      next: () => {
        this.isSubmitting = false;
        this.closeActionModal();
        this.loadLogs();
        this.loadProducts(); 
        this.cdr.markForCheck();
      },
      error: (err) => {
        this.isSubmitting = false;
        this.actionError = err.error?.message || 'Operation failed. Please try again.';
        this.cdr.markForCheck();
      }
    });
  }

  exportToExcel() {
    const dataToExport = this.getFilteredLogs().map(log => ({
      'ID': log.id,
      'Date': new Date(log.actionDate).toLocaleString(),
      'Product Name': log.productName,
      'Action': log.action,
      'Previous Qty': log.previousQuantity,
      'Qty Change': log.quantityChanged,
      'New Qty': log.newQuantity,
      'Performed By': log.performedBy || log.userName || '—',
      'Notes': log.notes || '—'
    }));
    this.exportExcel.export(dataToExport, 'Inventory_Logs_Report');
  }

  exportToPdf() {
    this.exportPdf.export('inventory-table', 'Inventory_Logs_Report');
  }
}

<div style="display: flex; flex-direction: column; gap: 20px;">
  
  <div class="page-header">
    <div>
      <h1 class="page-title">{{ 'SIDEBAR.INVENTORY' | translate }}</h1>
      <p class="page-subtitle">{{ 'INVENTORY.SUBTITLE' | translate }}</p>
    </div>
    <div style="display: flex; gap: 10px; flex-wrap: wrap; align-items: center;">
      <button class="btn btn-secondary" (click)="openActionModal('return')">
        {{ 'INVENTORY.RETURN_STOCK' | translate }}
      </button>
      <button *ngIf="isAdmin" class="btn btn-secondary" (click)="openActionModal('adjust')">
        {{ 'INVENTORY.ADJUST_STOCK' | translate }}
      </button>
      <button class="btn btn-danger" style="background: var(--danger-light); color: var(--danger); border: 1px solid rgba(239,68,68,0.2);" (click)="openActionModal('sell')">
        {{ 'INVENTORY.SELL_STOCK' | translate }}
      </button>
      <button class="btn btn-primary" (click)="openActionModal('add')">
        <lucide-icon [img]="icons.Plus" [size]="16"></lucide-icon>
        {{ 'INVENTORY.ADD_STOCK' | translate }}
      </button>
    </div>
  </div>

  <div class="card" style="padding: 12px 16px;">
    <div class="search-filter-row">
      
      <div class="search-wrapper" style="min-width: 220px; flex: 1; max-width: 320px;">
        <span class="search-icon"><lucide-icon [img]="icons.Search" [size]="16"></lucide-icon></span>
        <input 
          type="text" 
          [(ngModel)]="searchQuery" 
          (ngModelChange)="onFilterChange()"
          [placeholder]="'COMMON.SEARCH' | translate" 
          class="search-input"
        >
      </div>

      <div class="search-filter-controls">
        
        <select class="form-select filter-select" style="width: 180px;" [(ngModel)]="actionFilter" (ngModelChange)="onFilterChange()">
          <option value="">{{ 'INVENTORY.ACTION_FILTER' | translate }} ({{ 'COMMON.ALL' | translate }})</option>
          <option value="Add">{{ 'INVENTORY.ADD' | translate }}</option>
          <option value="Sell">{{ 'INVENTORY.SELL' | translate }}</option>
          <option value="Adjust">{{ 'INVENTORY.ADJUST' | translate }}</option>
          <option value="Return">{{ 'INVENTORY.RETURN' | translate }}</option>
        </select>

        <button class="btn btn-excel btn-sm" (click)="exportToExcel()" [disabled]="isLoading || getFilteredLogs().length === 0">
          Excel
        </button>
        <button class="btn btn-pdf btn-sm" (click)="exportToPdf()" [disabled]="isLoading || getFilteredLogs().length === 0">
          PDF
        </button>
      </div>
    </div>
  </div>

  <div class="card" style="padding: 0;">
    <div class="table-wrapper">
      <table id="inventory-table">
        <thead>
          <tr>
            <th>{{ 'COMMON.ID' | translate }}</th>
            <th>{{ 'INVENTORY.DATE' | translate }}</th>
            <th>{{ 'INVENTORY.PRODUCT' | translate }}</th>
            <th>{{ 'INVENTORY.ACTION' | translate }}</th>
            <th>{{ 'INVENTORY.PREVIOUS' | translate }}</th>
            <th>{{ 'INVENTORY.CHANGE' | translate }}</th>
            <th>{{ 'INVENTORY.NEW' | translate }}</th>
            <th>{{ 'INVENTORY.CHANGED_BY' | translate }}</th>
            <th>{{ 'INVENTORY.NOTES' | translate }}</th>
          </tr>
        </thead>
        <tbody>
          <ng-container *ngIf="isLoading">
            <tr *ngFor="let dummy of [1,2,3,4,5]">
              <td *ngFor="let col of [1,2,3,4,5,6,7,8,9]">
                <div class="skeleton" style="height: 16px; width: 75%;"></div>
              </td>
            </tr>
          </ng-container>

          <tr *ngIf="!isLoading && getFilteredLogs().length === 0">
            <td colspan="9">
              <div class="empty-state">
                <lucide-icon [img]="icons.ClipboardList" [size]="40"></lucide-icon>
                <p>{{ 'INVENTORY.NO_MOVEMENTS' | translate }}</p>
              </div>
            </td>
          </tr>

          <ng-container *ngIf="!isLoading && getFilteredLogs().length > 0">
            <tr *ngFor="let log of getFilteredLogs()">
              <td [attr.data-label]="'COMMON.ID' | translate" style="font-weight: bold; color: var(--text-muted);">#{{ log.id }}</td>
              <td [attr.data-label]="'INVENTORY.DATE' | translate" style="font-size: 12px; color: var(--text-muted); white-space: nowrap;">
                {{ log.actionDate | date:'medium' }}
              </td>
              <td [attr.data-label]="'INVENTORY.PRODUCT' | translate" class="font-bold">{{ log.productName }}</td>
              <td [attr.data-label]="'INVENTORY.ACTION' | translate">
                <span class="badge" 
                      [ngClass]="{
                        'badge-success': log.action === 'Add',
                        'badge-danger': log.action === 'Sell',
                        'badge-warning': log.action === 'Adjust',
                        'badge-info': log.action === 'Return'
                      }">
                  {{ ('INVENTORY.' + log.action.toUpperCase()) | translate }}
                </span>
              </td>
              <td [attr.data-label]="'INVENTORY.PREVIOUS' | translate">{{ log.previousQuantity }}</td>
              <td [attr.data-label]="'INVENTORY.CHANGE' | translate" class="font-bold" 
                  [ngStyle]="{
                    'color': log.action === 'Sell' ? 'var(--danger)' : 
                             (log.action === 'Add' ? 'var(--success)' : 
                             (log.action === 'Return' ? 'var(--info)' : 'var(--warning)'))
                  }">
                {{ log.action === 'Sell' ? '-' : '+' }}{{ log.quantityChanged }}
              </td>
              <td [attr.data-label]="'INVENTORY.NEW' | translate" class="font-bold">{{ log.newQuantity }}</td>
              <td [attr.data-label]="'INVENTORY.CHANGED_BY' | translate">
                <span class="badge badge-accent">{{ log.performedBy || '—' }}</span>
              </td>
              <td [attr.data-label]="'INVENTORY.NOTES' | translate" style="font-size: 12px; color: var(--text-secondary); max-width: 160px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;" [title]="log.notes">
                {{ log.notes || '—' }}
              </td>
            </tr>
          </ng-container>
        </tbody>
      </table>
    </div>

    <div class="pagination" *ngIf="totalPages > 0" style="display: flex; justify-content: space-between; align-items: center; width: 100%; padding: 16px 24px;">
      <div style="display: flex; align-items: center; gap: 12px;">
        <span class="pagination-info" style="margin: 0;">{{ 'PRODUCTS.PAGE' | translate }} {{ page }} / {{ totalPages }}</span>
        <select class="form-select" style="width: auto; padding: 4px 30px 4px 10px; font-size: 13px;" [(ngModel)]="pageSize" (ngModelChange)="onPageSizeChange()">
          <option [value]="5">5</option>
          <option [value]="10">10</option>
          <option [value]="15">15</option>
          <option [value]="25">25</option>
          <option [value]="50">50</option>
          <option [value]="100">100</option>
        </select>
      </div>
      <div class="pagination-controls">
        <button class="page-btn" [disabled]="page === 1" (click)="prevPage()">
          <lucide-icon [img]="icons.ChevronLeft" [size]="14"></lucide-icon>
        </button>
        <button *ngFor="let pg of getPagesArray()" class="page-btn" [ngClass]="{ active: page === pg }" (click)="goToPage(pg)">
          {{ pg }}
        </button>
        <button class="page-btn" [disabled]="page === totalPages" (click)="nextPage()">
          <lucide-icon [img]="icons.ChevronRight" [size]="14"></lucide-icon>
        </button>
      </div>
    </div>
  </div>

  <div class="custom-modal-overlay" *ngIf="actionModal" (click)="closeActionModal()">
    <div class="custom-modal" style="max-width: 440px;" (click)="$event.stopPropagation()">
      <div class="custom-modal-header">
        <h3 class="custom-modal-title">{{ getModalTitle() | translate }}</h3>
      </div>
      <div class="custom-modal-body" style="display: flex; flex-direction: column; gap: 14px; padding-top: 16px;">
        
        <div class="badge badge-danger" *ngIf="actionError" style="padding: 10px; border-radius: 8px; font-size: 13px;">
          {{ actionError }}
        </div>

        <div class="form-group">
          <label class="form-label">{{ 'INVENTORY.PRODUCT' | translate }} *</label>
          <select class="form-select" [(ngModel)]="selectedProductId">
            <option value="">{{ 'INVENTORY.SELECT_PRODUCT' | translate }}</option>
            <option *ngFor="let p of products" [value]="p.id">
              {{ p.name }} ({{ 'PRODUCTS.QUANTITY' | translate }}: {{ p.quantity }} {{ p.unitName }})
            </option>
          </select>
        </div>
        
        <div class="form-group">
          <label class="form-label">{{ getQtyLabel() | translate }} *</label>
          <input class="form-input" type="number" [min]="actionModal === 'adjust' ? 0 : 1" [(ngModel)]="quantity" />
        </div>
        
        <div class="form-group">
          <label class="form-label">{{ 'INVENTORY.NOTES' | translate }}</label>
          <textarea class="form-textarea" rows="2" [(ngModel)]="notes"></textarea>
        </div>

      </div>
      <div class="custom-modal-footer">
        <button class="btn btn-ghost" (click)="closeActionModal()">
          {{ 'COMMON.CANCEL' | translate }}
        </button>
        <button
          class="btn btn-primary"
          [disabled]="!selectedProductId || quantity < 0 || isSubmitting"
          (click)="submitAction()"
        >
          <span class="spinner" *ngIf="isSubmitting"></span>
          {{ 'COMMON.SAVE' | translate }}
        </button>
      </div>
    </div>
  </div>
</div>

// inventory-frontend/src/pages/Inventory/Inventory.tsx
import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useTranslation } from 'react-i18next'
import { Plus, ChevronLeft, ChevronRight, ClipboardList, Download } from 'lucide-react'
import * as XLSX from 'xlsx'
import { inventoryApi, productsApi } from '../../api/services'
import { useToastStore, useAuthStore } from '../../store'
import { format } from 'date-fns'

type ActionType = 'add' | 'sell' | 'adjust' | 'return' | null

export default function Inventory() {
  const { t } = useTranslation()
  const { addToast } = useToastStore()
  const { user } = useAuthStore()
  const qc = useQueryClient()

  const [page, setPage] = useState(1)
  const [actionFilter, setActionFilter] = useState('')
  const [actionModal, setActionModal] = useState<ActionType>(null)
  const [productId, setProductId] = useState<number | ''>('')
  const [quantity, setQuantity] = useState<number>(1)
  const [notes, setNotes] = useState('')

  const { data, isLoading } = useQuery({
    queryKey: ['inventory-logs', page, actionFilter],
    queryFn: () => inventoryApi.getLogs({ page, pageSize: 20, action: actionFilter || undefined })
  })

  const { data: productsData } = useQuery({
    queryKey: ['products-all'],
    queryFn: () => productsApi.getAll({ page: 1, pageSize: 1000 })
  })

  const result = data?.data?.data
  const logs = result?.items || []
  const totalPages = result?.totalPages || 1
  const allProducts = productsData?.data?.data?.items || []

  const mutation = useMutation({
    mutationFn: async () => {
      if (!productId) return
      const dto = { productId, notes }
      switch (actionModal) {
        case 'add':    return inventoryApi.add({ ...dto, quantityToAdd: quantity })
        case 'sell':   return inventoryApi.sell({ ...dto, quantityToSell: quantity })
        case 'adjust': return inventoryApi.adjust({ ...dto, newQuantity: quantity })
        case 'return': return inventoryApi.return({ ...dto, quantityToReturn: quantity })
      }
    },
    onSuccess: (res: any) => {
      addToast('success', res?.data?.message || 'Operation successful')
      qc.invalidateQueries({ queryKey: ['inventory-logs'] })
      qc.invalidateQueries({ queryKey: ['products'] })
      qc.invalidateQueries({ queryKey: ['dashboard-stats'] })
      setActionModal(null)
      setProductId('')
      setQuantity(1)
      setNotes('')
    },
    onError: (err: any) => addToast('error', err?.response?.data?.message || 'Operation failed')
  })

  const actionColors: Record<string, string> = {
    Add: 'var(--success)', Sell: 'var(--danger)',
    Adjust: 'var(--warning)', Return: 'var(--info)'
  }

  const actionBadges: Record<string, string> = {
    Add: 'badge-success', Sell: 'badge-danger',
    Adjust: 'badge-warning', Return: 'badge-info'
  }

  const getModalTitle = () => {
    switch (actionModal) {
      case 'add': return t('addStock')
      case 'sell': return t('sellStock')
      case 'adjust': return t('adjustStock')
      case 'return': return t('returnStock')
      default: return ''
    }
  }

  const getQtyLabel = () => {
    switch (actionModal) {
      case 'add': return t('quantityToAdd')
      case 'sell': return t('quantityToSell')
      case 'adjust': return t('newQuantity')
      case 'return': return t('quantityToReturn')
      default: return t('quantity')
    }
  }

  const exportToExcel = () => {
    if (!logs.length) return
    const exportData = logs.map((log: any) => ({
      ID: log.id,
      Date: format(new Date(log.actionDate), 'dd MMM yyyy HH:mm'),
      Product: log.productName,
      Action: log.action,
      'Previous Qty': log.previousQuantity,
      'Changed Qty': log.quantityChanged,
      'New Qty': log.newQuantity,
      'Performed By': log.performedBy || 'Unknown',
      Notes: log.notes || ''
    }))
    
    const ws = XLSX.utils.json_to_sheet(exportData)
    const wb = XLSX.utils.book_new()
    XLSX.utils.book_append_sheet(wb, ws, 'InventoryLogs')
    XLSX.writeFile(wb, `InventoryLogs_Export_${new Date().toISOString().split('T')[0]}.xlsx`)
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
      {/* Header */}
      <div className="page-header">
        <div>
          <h1 className="page-title">{t('inventory')}</h1>
          <p className="page-subtitle">{t('recentMovements')}</p>
        </div>
        <div style={{ display: 'flex', gap: 10 }}>
          <button className="btn btn-ghost" onClick={exportToExcel} disabled={!logs.length}>
            <Download size={16} />
          </button>
          <button className="btn btn-secondary" onClick={() => setActionModal('return')}>
            {t('returnStock')}
          </button>
          {user?.isAdmin && (
            <button className="btn btn-secondary" onClick={() => setActionModal('adjust')}>
              {t('adjustStock')}
            </button>
          )}
          <button className="btn btn-danger" style={{ background: 'var(--danger-light)', color: 'var(--danger)', border: '1px solid rgba(239,68,68,0.2)' }} onClick={() => setActionModal('sell')}>
            {t('sellStock')}
          </button>
          <button className="btn btn-primary" onClick={() => setActionModal('add')}>
            <Plus size={16} /> {t('addStock')}
          </button>
        </div>
      </div>

      {/* Filters */}
      <div className="card" style={{ padding: '14px 20px' }}>
        <div style={{ display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap' }}>
          <label className="form-label" style={{ margin: 0 }}>{t('action')}:</label>
          {['', 'Add', 'Sell', 'Adjust', 'Return'].map(a => (
            <button
              key={a}
              className={`btn btn-ghost btn-sm ${actionFilter === a ? 'active-filter' : ''}`}
              style={a && actionFilter === a ? { background: `${actionColors[a]}20`, color: actionColors[a] } : {}}
              onClick={() => { setActionFilter(a); setPage(1) }}
            >
              {a || t('allActions')}
            </button>
          ))}
        </div>
      </div>

      {/* Table */}
      <div className="card" style={{ padding: 0 }}>
        <div className="table-wrapper">
          <table>
            <thead>
              <tr>
                <th>{t('date')}</th>
                <th>{t('product')}</th>
                <th>{t('action')}</th>
                <th>{t('previous')}</th>
                <th>{t('change')}</th>
                <th>{t('new')}</th>
                <th>{t('changedBy')}</th>
                <th>{t('notes')}</th>
              </tr>
            </thead>
            <tbody>
              {isLoading
                ? Array.from({ length: 8 }).map((_, i) => (
                    <tr key={i}>
                      {Array.from({ length: 8 }).map((__, j) => (
                        <td key={j}><div className="skeleton" style={{ height: 16, width: '75%' }} /></td>
                      ))}
                    </tr>
                  ))
                : logs.length === 0
                ? (
                    <tr>
                      <td colSpan={8}>
                        <div className="empty-state">
                          <ClipboardList size={40} />
                          <p>{t('noLogs')}</p>
                        </div>
                      </td>
                    </tr>
                  )
                : logs.map((log: any) => (
                    <tr key={log.id}>
                      <td style={{ fontSize: 12, color: 'var(--text-muted)', whiteSpace: 'nowrap' }}>
                        {format(new Date(log.actionDate), 'dd MMM yyyy HH:mm')}
                      </td>
                      <td style={{ fontWeight: 600 }}>{log.productName}</td>
                      <td>
                        <span className={`badge ${actionBadges[log.action] || 'badge-accent'}`}>
                          {log.action}
                        </span>
                      </td>
                      <td style={{ color: 'var(--text-secondary)' }}>{log.previousQuantity}</td>
                      <td style={{ fontWeight: 700, color: actionColors[log.action] }}>
                        {log.action === 'Sell' ? '-' : '+'}{log.quantityChanged}
                      </td>
                      <td style={{ fontWeight: 700 }}>{log.newQuantity}</td>
                      <td style={{ fontSize: 12 }}>
                        <span className="badge badge-accent">{log.performedBy || '—'}</span>
                      </td>
                      <td style={{ fontSize: 12, color: 'var(--text-muted)', maxWidth: 160, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                        {log.notes || '—'}
                      </td>
                    </tr>
                  ))
              }
            </tbody>
          </table>
        </div>
        {/* Pagination */}
        <div className="pagination">
          <span className="pagination-info">{t('page')} {page} {t('of')} {totalPages}</span>
          <div className="pagination-controls">
            <button className="page-btn" disabled={page === 1} onClick={() => setPage(p => p - 1)}>
              <ChevronLeft size={14} />
            </button>
            <button className="page-btn" disabled={page === totalPages} onClick={() => setPage(p => p + 1)}>
              <ChevronRight size={14} />
            </button>
          </div>
        </div>
      </div>

      {/* Action Modal */}
      {actionModal && (
        <div className="modal-overlay" onClick={() => setActionModal(null)}>
          <div className="modal" style={{ maxWidth: 440 }} onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h3 className="modal-title">{getModalTitle()}</h3>
            </div>
            <div className="modal-body" style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
              <div className="form-group">
                <label className="form-label">{t('product')} *</label>
                <select
                  className="form-select"
                  value={productId}
                  onChange={e => setProductId(Number(e.target.value))}
                >
                  <option value="">-- Select Product --</option>
                  {allProducts.map((p: any) => (
                    <option key={p.id} value={p.id}>
                      {p.name} (Stock: {p.quantity})
                    </option>
                  ))}
                </select>
              </div>
              <div className="form-group">
                <label className="form-label">{getQtyLabel()} *</label>
                <input
                  className="form-input"
                  type="number"
                  min={actionModal === 'adjust' ? 0 : 1}
                  value={quantity}
                  onChange={e => setQuantity(Number(e.target.value))}
                />
              </div>
              <div className="form-group">
                <label className="form-label">{t('notes')}</label>
                <textarea
                  className="form-textarea"
                  rows={2}
                  value={notes}
                  onChange={e => setNotes(e.target.value)}
                />
              </div>
            </div>
            <div className="modal-footer">
              <button className="btn btn-ghost" onClick={() => setActionModal(null)}>{t('cancel')}</button>
              <button
                className="btn btn-primary"
                disabled={!productId || quantity < 0 || mutation.isPending}
                onClick={() => mutation.mutate()}
              >
                {mutation.isPending ? <span className="spinner" /> : null}
                {t('confirm')}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
