// inventory-frontend/src/app/features/products/products.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { LucideAngularModule, Search, Package, Edit, Trash2, ChevronLeft, ChevronRight, LayoutGrid, List, Plus } from 'lucide-angular';
import { ProductService } from '../../core/services/product.service';
import { AuthService } from '../../core/services/auth.service';
import { TranslatePipe } from '@ngx-translate/core';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'app-products',
  imports: [CommonModule, FormsModule, LucideAngularModule, TranslatePipe],
  templateUrl: './products.component.html',
  styleUrl: './products.component.css'
})
export class ProductsComponent implements OnInit {
  readonly icons = { Search, Package, Edit, Trash2, ChevronLeft, ChevronRight, LayoutGrid, List, Plus };

  products: any[] = [];
  totalCount = 0;
  totalPages = 1;
  page = 1;
  searchQuery = '';
  isLoading = false;
  viewMode: 'table' | 'grid' = 'table';

  categories: any[] = [];

  deleteConfirm: any = null;
  isDeleting = false;

  user: any;

  constructor(
    private productService: ProductService,
    private authService: AuthService,
    private http: HttpClient
  ) {
    this.user = this.authService.getCurrentUser();
  }

  ngOnInit() {
    this.loadProducts();
    this.loadCategories();
  }

  loadCategories() {
    this.http.get<any>(`${environment.apiUrl}/lookup/categories`).subscribe({
      next: (res) => this.categories = res.data || [],
      error: () => {}
    });
  }

  get isAdmin() {
    return this.user?.['http://schemas.microsoft.com/ws/2008/06/identity/claims/role'] === 'Manager';
  }

  loadProducts() {
    this.isLoading = true;
    this.productService.getProducts(this.page, 15, this.searchQuery).subscribe({
      next: (res) => {
        this.products = res.data?.items || [];
        this.totalCount = res.data?.totalCount || 0;
        this.totalPages = res.data?.totalPages || 1;
        this.isLoading = false;
      },
      error: () => this.isLoading = false
    });
  }

  onSearch() {
    this.page = 1;
    this.loadProducts();
  }

  prevPage() {
    if (this.page > 1) {
      this.page--;
      this.loadProducts();
    }
  }

  nextPage() {
    if (this.page < this.totalPages) {
      this.page++;
      this.loadProducts();
    }
  }

  goToPage(pg: number) {
    this.page = pg;
    this.loadProducts();
  }

  getPagesArray() {
    const pages = [];
    const maxPages = Math.min(this.totalPages, 5);
    for (let i = 1; i <= maxPages; i++) {
      pages.push(i);
    }
    return pages;
  }

  getStockBadgeClass(quantity: number, minQuantity: number) {
    if (quantity === 0) return 'badge-danger';
    if (quantity <= minQuantity) return 'badge-warning';
    return 'badge-success';
  }

  getStockBadgeText(quantity: number, minQuantity: number) {
    if (quantity === 0) return 'PRODUCTS.OUT_OF_STOCK';
    if (quantity <= minQuantity) return 'PRODUCTS.LOW_STOCK';
    return 'PRODUCTS.IN_STOCK';
  }

  confirmDelete(product: any) {
    this.deleteConfirm = product;
  }

  deleteProduct() {
    if (!this.deleteConfirm) return;
    this.isDeleting = true;
    this.productService.deleteProduct(this.deleteConfirm.id).subscribe({
      next: () => {
        this.isDeleting = false;
        this.deleteConfirm = null;
        this.loadProducts();
      },
      error: () => this.isDeleting = false
    });
  }

  // Product Modal
  showProductModal = false;
  isSavingProduct = false;
  editProduct: any = null;
  productForm: any = {
    name: '', sku: '', categoryId: null, price: 0, unit: '', minQuantity: 0, supplierId: null, description: ''
  };

  openAddProduct() {
    this.editProduct = null;
    this.productForm = { name: '', sku: '', categoryId: null, price: 0, unit: '', minQuantity: 0, supplierId: null, description: '' };
    this.showProductModal = true;
  }

  openEditProduct(product: any) {
    this.editProduct = product;
    this.productForm = {
      name: product.name,
      sku: product.sku,
      categoryId: product.categoryId,
      price: product.price,
      unit: product.unit || product.unitName,
      minQuantity: product.minQuantity,
      supplierId: product.supplierId,
      description: product.description || ''
    };
    this.showProductModal = true;
  }

  submitProduct() {
    this.isSavingProduct = true;
    const payload = {
      name: this.productForm.name,
      sku: this.productForm.sku,
      categoryId: this.productForm.categoryId ? Number(this.productForm.categoryId) : null,
      price: Number(this.productForm.price),
      unitId: null,
      minQuantity: Number(this.productForm.minQuantity),
      supplierId: this.productForm.supplierId ? Number(this.productForm.supplierId) : null,
      description: this.productForm.description || '',
      purchasePrice: 0
    };
    const req = this.editProduct
      ? this.productService.updateProduct(this.editProduct.id, payload)
      : this.productService.createProduct(payload);

    req.subscribe({
      next: () => {
        this.isSavingProduct = false;
        this.showProductModal = false;
        this.loadProducts();
      },
      error: () => this.isSavingProduct = false
    });
  }
}

<div style="display: flex; flex-direction: column; gap: 20px;">
  <!-- Header -->
  <div class="page-header" style="display: flex; justify-content: space-between; align-items: center;">
     <div>
      <h1 class="page-title">{{ 'PRODUCTS.TITLE' | translate }}</h1>
      <p class="page-subtitle">{{ 'PRODUCTS.ITEMS_COUNT' | translate:{count: totalCount} }}</p>
    </div>
    <div style="display: flex; gap: 12px; align-items: center;">
      <!-- View mode toggle -->
      <div class="view-toggle">
        <button class="view-btn" [ngClass]="{ active: viewMode === 'table' }" (click)="viewMode = 'table'" [title]="'PRODUCTS.LIST_VIEW' | translate">
          <lucide-icon [img]="icons.List" [size]="16"></lucide-icon>
        </button>
        <button class="view-btn" [ngClass]="{ active: viewMode === 'grid' }" (click)="viewMode = 'grid'" [title]="'PRODUCTS.GRID_VIEW' | translate">
          <lucide-icon [img]="icons.LayoutGrid" [size]="16"></lucide-icon>
        </button>
      </div>
      <button class="btn btn-primary" (click)="openAddProduct()" style="display: flex; align-items: center; gap: 6px;">
        <lucide-icon [img]="icons.Plus" [size]="16"></lucide-icon> {{ 'PRODUCTS.ADD_PRODUCT' | translate }}
      </button>
    </div>
  </div>

  <!-- Search -->
  <div class="card" style="padding: 14px 20px;">
    <div class="search-wrapper">
      <span class="search-icon"><lucide-icon [img]="icons.Search" [size]="16"></lucide-icon></span>
      <input
        class="search-input"
        [placeholder]="'COMMON.SEARCH' | translate"
        [(ngModel)]="searchQuery"
        (ngModelChange)="onSearch()"
      />
    </div>
  </div>

  <!-- Table View -->
  <div class="card" style="padding: 0;" *ngIf="viewMode === 'table'">
    <div class="table-wrapper">
      <table>
        <thead>
          <tr>
            <th>{{ 'PRODUCTS.PRODUCT_NAME' | translate }}</th>
            <th>{{ 'PRODUCTS.SKU' | translate }}</th>
            <th>{{ 'PRODUCTS.CATEGORY' | translate }}</th>
            <th>{{ 'PRODUCTS.PRICE' | translate }}</th>
            <th>{{ 'PRODUCTS.QUANTITY' | translate }}</th>
            <th>{{ 'COMMON.STATUS' | translate }}</th>
            <th>{{ 'COMMON.ACTIONS' | translate }}</th>
          </tr>
        </thead>
        <tbody>
          <!-- Loading state -->
          <ng-container *ngIf="isLoading">
            <tr *ngFor="let dummy of [1,2,3,4,5]">
              <td *ngFor="let col of [1,2,3,4,5,6,7]">
                <div class="skeleton" style="height: 16px; width: 70%;"></div>
              </td>
            </tr>
          </ng-container>

          <!-- Empty state -->
          <tr *ngIf="!isLoading && products.length === 0">
            <td colspan="7">
              <div class="empty-state">
                <lucide-icon [img]="icons.Package" [size]="40"></lucide-icon>
                <p>{{ 'PRODUCTS.NO_PRODUCTS' | translate }}</p>
              </div>
            </td>
          </tr>

          <!-- Data rows -->
          <ng-container *ngIf="!isLoading && products.length > 0">
            <tr *ngFor="let p of products">
              <td>
                <div style="display: flex; align-items: center; gap: 10px;">
                  <div class="product-icon-mini">
                    <lucide-icon [img]="icons.Package" [size]="14"></lucide-icon>
                  </div>
                  <div>
                    <div style="font-weight: 600; font-size: 14px;">{{ p.name }}</div>
                    <div *ngIf="p.supplier" style="font-size: 12px; color: var(--text-muted);">{{ p.supplier }}</div>
                  </div>
                </div>
              </td>
              <td>
                <code class="sku-code">{{ p.sku || '—' }}</code>
              </td>
              <td>
                <span class="badge badge-info">{{ p.category }}</span>
              </td>
              <td>
                <span style="font-weight: 600; color: var(--success);">
                  {{ p.price | currency }}
                </span>
              </td>
              <td>
                <div style="display: flex; flex-direction: column; gap: 2px;">
                  <span style="font-weight: 700;">{{ p.quantity }} <span style="font-size: 11px; color: var(--text-muted);">{{ p.unit }}</span></span>
                  <span style="font-size: 11px; color: var(--text-muted);">{{ 'PRODUCTS.MIN' | translate }}: {{ p.minQuantity }}</span>
                </div>
              </td>
              <td>
                <span class="badge" [ngClass]="getStockBadgeClass(p.quantity, p.minQuantity)">
                  {{ getStockBadgeText(p.quantity, p.minQuantity) | translate }}
                </span>
              </td>
              <td>
                <div style="display: flex; gap: 6px;">
                  <button class="btn btn-ghost btn-icon btn-sm" (click)="openEditProduct(p)" [title]="'COMMON.EDIT' | translate">
                    <lucide-icon [img]="icons.Edit" [size]="14"></lucide-icon>
                  </button>
                  <button *ngIf="isAdmin" class="btn btn-danger btn-icon btn-sm" (click)="confirmDelete(p)" [title]="'COMMON.DELETE' | translate">
                    <lucide-icon [img]="icons.Trash2" [size]="14"></lucide-icon>
                  </button>
                </div>
              </td>
            </tr>
          </ng-container>
        </tbody>
      </table>
    </div>

    <!-- Pagination -->
    <div class="pagination" *ngIf="totalPages > 0">
      <span class="pagination-info">{{ 'PRODUCTS.PAGE' | translate }} {{ page }} / {{ totalPages }}</span>
      <div class="pagination-controls">
        <button class="page-btn" [disabled]="page === 1" (click)="prevPage()">
          <lucide-icon [img]="icons.ChevronLeft" [size]="14"></lucide-icon>
        </button>
        <button *ngFor="let pg of getPagesArray()" class="page-btn" [ngClass]="{ active: page === pg }" (click)="goToPage(pg)">
          {{ pg }}
        </button>
        <button class="page-btn" [disabled]="page === totalPages" (click)="nextPage()">
          <lucide-icon [img]="icons.ChevronRight" [size]="14"></lucide-icon>
        </button>
      </div>
    </div>
  </div>

  <!-- Grid View -->
  <div class="products-grid" *ngIf="viewMode === 'grid'">
    <!-- Loading state -->
    <ng-container *ngIf="isLoading">
      <div *ngFor="let dummy of [1,2,3,4,5,6,7,8]" class="skeleton" style="height: 180px; border-radius: 12px;"></div>
    </ng-container>

    <!-- Data cards -->
    <ng-container *ngIf="!isLoading">
      <div *ngFor="let p of products" class="product-card">
        <div class="product-card-header">
          <div class="product-card-icon">
            <lucide-icon [img]="icons.Package" [size]="20"></lucide-icon>
          </div>
          <span class="badge" [ngClass]="getStockBadgeClass(p.quantity, p.minQuantity)">
            {{ getStockBadgeText(p.quantity, p.minQuantity) | translate }}
          </span>
        </div>
        <h3 class="product-card-name">{{ p.name }}</h3>
        <p class="product-card-sku">{{ p.sku }}</p>
        <div class="product-card-stats">
          <div>
            <span class="product-card-price">{{ p.price | currency }}</span>
            <span class="product-card-unit">/ {{ p.unit }}</span>
          </div>
          <span class="badge badge-info">{{ p.category }}</span>
        </div>
        <div class="product-card-qty">
          <span>{{ 'PRODUCTS.QUANTITY' | translate }}: <strong>{{ p.quantity }}</strong></span>
          <span class="text-muted">{{ 'PRODUCTS.MIN' | translate }}: {{ p.minQuantity }}</span>
        </div>
        <div class="product-card-actions">
          <button class="btn btn-ghost btn-sm" (click)="openEditProduct(p)">
            <lucide-icon [img]="icons.Edit" [size]="13"></lucide-icon> {{ 'COMMON.EDIT' | translate }}
          </button>
          <button *ngIf="isAdmin" class="btn btn-danger btn-sm" (click)="confirmDelete(p)">
            <lucide-icon [img]="icons.Trash2" [size]="13"></lucide-icon> {{ 'COMMON.DELETE' | translate }}
          </button>
        </div>
      </div>
    </ng-container>
  </div>

  <!-- Delete Confirm Modal -->
  <div class="custom-modal-overlay" *ngIf="deleteConfirm" (click)="deleteConfirm = null">
    <div class="custom-modal" style="max-width: 400px;" (click)="$event.stopPropagation()">
      <div class="custom-modal-header">
        <h3 class="custom-modal-title" style="color: var(--danger);">
          <lucide-icon [img]="icons.Trash2" [size]="18" style="display: inline; margin-right: 8px;"></lucide-icon>
          {{ 'PRODUCTS.CONFIRM_DELETE_TITLE' | translate }}
        </h3>
      </div>
      <div class="custom-modal-body">
        <p style="color: var(--text-secondary); font-size: 14px;">
          {{ 'PRODUCTS.CONFIRM_DELETE_MSG' | translate }}
        </p>
        <p style="margin-top: 8px; font-weight: 600; color: var(--text-primary);">
          "{{ deleteConfirm.name }}"
        </p>
      </div>
      <div class="custom-modal-footer">
        <button class="btn btn-ghost" (click)="deleteConfirm = null">{{ 'COMMON.CANCEL' | translate }}</button>
        <button class="btn btn-danger" (click)="deleteProduct()" [disabled]="isDeleting">
          <span class="spinner" *ngIf="isDeleting"></span>
          <lucide-icon [img]="icons.Trash2" [size]="14" *ngIf="!isDeleting"></lucide-icon>
          {{ 'COMMON.DELETE' | translate }}
        </button>
      </div>
    </div>
  </div>

  <!-- Product Modal -->
  <div class="custom-modal-overlay" *ngIf="showProductModal" (click)="showProductModal = false">
    <div class="custom-modal" style="max-width: 500px;" (click)="$event.stopPropagation()">
      <div class="custom-modal-header">
        <h3 class="custom-modal-title">
          <lucide-icon [img]="icons.Package" [size]="18" style="display: inline; margin-right: 8px;"></lucide-icon>
          {{ editProduct ? ('PRODUCTS.EDIT_PRODUCT' | translate) : ('PRODUCTS.ADD_PRODUCT' | translate) }}
        </h3>
      </div>
      <div class="custom-modal-body">
        <div class="form-group">
          <label class="form-label">{{ 'PRODUCTS.PRODUCT_NAME' | translate }} *</label>
          <input class="form-input" [(ngModel)]="productForm.name" />
        </div>
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px;">
          <div class="form-group">
            <label class="form-label">{{ 'PRODUCTS.SKU' | translate }}</label>
            <input class="form-input" [(ngModel)]="productForm.sku" />
          </div>
          <div class="form-group">
            <label class="form-label">{{ 'PRODUCTS.CATEGORY' | translate }} *</label>
            <select class="form-select" [(ngModel)]="productForm.categoryId">
              <option [ngValue]="null">{{ 'PRODUCTS.SELECT_CATEGORY' | translate }}</option>
              <option *ngFor="let cat of categories" [ngValue]="cat.id">{{ cat.name }}</option>
            </select>
          </div>
        </div>
        <div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 12px;">
          <div class="form-group">
            <label class="form-label">{{ 'PRODUCTS.PRICE' | translate }} *</label>
            <input class="form-input" type="number" step="0.01" [(ngModel)]="productForm.price" />
          </div>
          <div class="form-group">
            <label class="form-label">{{ 'PRODUCTS.UNIT' | translate }}</label>
            <input class="form-input" [(ngModel)]="productForm.unit" [placeholder]="'PRODUCTS.UNIT_PLACEHOLDER' | translate" />
          </div>
          <div class="form-group">
            <label class="form-label">{{ 'PRODUCTS.MIN_QTY' | translate }} *</label>
            <input class="form-input" type="number" [(ngModel)]="productForm.minQuantity" />
          </div>
        </div>
        <div class="form-group" style="margin-bottom: 0;">
          <label class="form-label">{{ 'COMMON.DESCRIPTION' | translate }}</label>
          <textarea class="form-textarea" rows="2" [(ngModel)]="productForm.description"></textarea>
        </div>
      </div>
      <div class="custom-modal-footer">
        <button class="btn btn-ghost" (click)="showProductModal = false">{{ 'COMMON.CANCEL' | translate }}</button>
        <button class="btn btn-primary" (click)="submitProduct()" [disabled]="!productForm.name || !productForm.categoryId || isSavingProduct">
          <span class="spinner" *ngIf="isSavingProduct"></span>
          {{ 'COMMON.SAVE' | translate }}
        </button>
      </div>
    </div>
  </div>
</div>

// inventory-frontend/src/pages/Products/Products.tsx
import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useTranslation } from 'react-i18next'
import {
  Plus, Search, Filter, Edit, Trash2, Package,
  AlertTriangle, ChevronLeft, ChevronRight, X,
  RefreshCw, LayoutGrid, List, Download
} from 'lucide-react'
import * as XLSX from 'xlsx'
import { productsApi } from '../../api/services'
import { useAuthStore, useToastStore } from '../../store'
import ProductModal from './ProductModal'
import './Products.css'

interface QueryParams {
  page: number
  pageSize: number
  search: string
  category: string
  sortBy: string
  sortOrder: string
  isLowStock?: boolean
}

export default function Products() {
  const { t } = useTranslation()
  const { user } = useAuthStore()
  const { addToast } = useToastStore()
  const qc = useQueryClient()

  const [params, setParams] = useState<QueryParams>({
    page: 1, pageSize: 10, search: '', category: '',
    sortBy: 'name', sortOrder: 'asc'
  })
  const [searchInput, setSearchInput] = useState('')
  const [viewMode, setViewMode] = useState<'table' | 'grid'>('table')
  const [showModal, setShowModal] = useState(false)
  const [editProduct, setEditProduct] = useState<any>(null)
  const [deleteConfirm, setDeleteConfirm] = useState<any>(null)

  const { data, isLoading, refetch } = useQuery({
    queryKey: ['products', params],
    queryFn: () => productsApi.getAll(params)
  })

  const { data: categoriesData } = useQuery({
    queryKey: ['product-categories'],
    queryFn: () => productsApi.getCategories()
  })

  const deleteMutation = useMutation({
    mutationFn: (id: number) => productsApi.delete(id),
    onSuccess: () => {
      addToast('success', 'Product deleted successfully')
      setDeleteConfirm(null)
      qc.invalidateQueries({ queryKey: ['products'] })
      qc.invalidateQueries({ queryKey: ['dashboard-stats'] })
    },
    onError: () => addToast('error', 'Failed to delete product')
  })

  const result = data?.data?.data
  const products = result?.items || []
  const totalCount = result?.totalCount || 0
  const totalPages = result?.totalPages || 1
  const categories: string[] = categoriesData?.data?.data || []

  const handleSearch = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      setParams(p => ({ ...p, search: searchInput, page: 1 }))
    }
  }

  const handleSort = (field: string) => {
    setParams(p => ({
      ...p,
      sortBy: field,
      sortOrder: p.sortBy === field && p.sortOrder === 'asc' ? 'desc' : 'asc',
      page: 1
    }))
  }

  const getStockBadge = (qty: number, min: number) => {
    if (qty === 0) return <span className="badge badge-danger">{t('outOfStockBadge')}</span>
    if (qty <= min) return <span className="badge badge-warning">{t('lowStockBadge')}</span>
    return <span className="badge badge-success">{t('inStock')}</span>
  }

  const exportToExcel = () => {
    if (!products.length) return
    const exportData = products.map((p: any) => ({
      ID: p.id,
      Name: p.name,
      SKU: p.sku,
      Category: p.category,
      Price: p.price,
      Quantity: p.quantity,
      'Min Quantity': p.minQuantity,
      Unit: p.unit,
      Supplier: p.supplier,
      Status: p.quantity === 0 ? 'Out of Stock' : p.quantity <= p.minQuantity ? 'Low Stock' : 'In Stock'
    }))
    
    const ws = XLSX.utils.json_to_sheet(exportData)
    const wb = XLSX.utils.book_new()
    XLSX.utils.book_append_sheet(wb, ws, 'Products')
    XLSX.writeFile(wb, `Products_Export_${new Date().toISOString().split('T')[0]}.xlsx`)
  }

  return (
    <div className="products-page">
      {/* Header */}
      <div className="page-header">
        <div>
          <h1 className="page-title">{t('products')}</h1>
          <p className="page-subtitle">{totalCount} {t('items')} {t('total')}</p>
        </div>
        <div style={{ display: 'flex', gap: 10 }}>
          <button className="btn btn-secondary" onClick={exportToExcel} disabled={!products.length}>
            <Download size={16} />
            Export Excel
          </button>
          {user?.isAdmin && (
            <button className="btn btn-primary" onClick={() => { setEditProduct(null); setShowModal(true) }}>
              <Plus size={16} />
              {t('addProduct')}
            </button>
          )}
        </div>
      </div>

      {/* Filters Bar */}
      <div className="card" style={{ padding: '16px 20px' }}>
        <div className="filters-row">
          {/* Search */}
          <div className="search-wrapper" style={{ flex: 1, maxWidth: 360 }}>
            <span className="search-icon"><Search size={16} /></span>
            <input
              className="search-input"
              placeholder={t('search')}
              value={searchInput}
              onChange={e => setSearchInput(e.target.value)}
              onKeyDown={handleSearch}
            />
            {searchInput && (
              <button
                style={{ position: 'absolute', right: 10, top: '50%', transform: 'translateY(-50%)', background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-muted)' }}
                onClick={() => { setSearchInput(''); setParams(p => ({ ...p, search: '', page: 1 })) }}
              >
                <X size={14} />
              </button>
            )}
          </div>

          {/* Category filter */}
          <select
            className="form-select"
            style={{ width: 'auto', minWidth: 160 }}
            value={params.category}
            onChange={e => setParams(p => ({ ...p, category: e.target.value, page: 1 }))}
          >
            <option value="">{t('allCategories')}</option>
            {categories.map(c => <option key={c} value={c}>{c}</option>)}
          </select>

          {/* Low stock filter */}
          <button
            className={`btn btn-ghost btn-sm ${params.isLowStock ? 'active-filter' : ''}`}
            onClick={() => setParams(p => ({ ...p, isLowStock: p.isLowStock ? undefined : true, page: 1 }))}
          >
            <AlertTriangle size={14} />
            {t('lowStock')}
          </button>

          {/* View mode */}
          <div className="view-toggle">
            <button
              className={`view-btn ${viewMode === 'table' ? 'active' : ''}`}
              onClick={() => setViewMode('table')}
            >
              <List size={15} />
            </button>
            <button
              className={`view-btn ${viewMode === 'grid' ? 'active' : ''}`}
              onClick={() => setViewMode('grid')}
            >
              <LayoutGrid size={15} />
            </button>
          </div>

          {/* Refresh */}
          <button className="btn btn-ghost btn-icon btn-sm" onClick={() => refetch()} title="Refresh">
            <RefreshCw size={15} className={isLoading ? 'spinning' : ''} />
          </button>
        </div>
      </div>

      {/* Table View */}
      {viewMode === 'table' && (
        <div className="card" style={{ padding: 0 }}>
          <div className="table-wrapper">
            <table>
              <thead>
                <tr>
                  <th onClick={() => handleSort('name')} className="sortable">
                    {t('productName')} {params.sortBy === 'name' && (params.sortOrder === 'asc' ? '↑' : '↓')}
                  </th>
                  <th>{t('sku')}</th>
                  <th>{t('category')}</th>
                  <th onClick={() => handleSort('price')} className="sortable">
                    {t('price')} {params.sortBy === 'price' && (params.sortOrder === 'asc' ? '↑' : '↓')}
                  </th>
                  <th onClick={() => handleSort('quantity')} className="sortable">
                    {t('quantity')} {params.sortBy === 'quantity' && (params.sortOrder === 'asc' ? '↑' : '↓')}
                  </th>
                  <th>Status</th>
                  <th>{t('actions')}</th>
                </tr>
              </thead>
              <tbody>
                {isLoading ? (
                  Array.from({ length: 5 }).map((_, i) => (
                    <tr key={i}>
                      {Array.from({ length: 7 }).map((__, j) => (
                        <td key={j}>
                          <div className="skeleton" style={{ height: 18, width: '80%' }} />
                        </td>
                      ))}
                    </tr>
                  ))
                ) : products.length === 0 ? (
                  <tr>
                    <td colSpan={7}>
                      <div className="empty-state">
                        <Package size={40} />
                        <p>{t('noProducts')}</p>
                      </div>
                    </td>
                  </tr>
                ) : (
                  products.map((p: any) => (
                    <tr key={p.id}>
                      <td>
                        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                          <div className="product-icon-mini">
                            <Package size={14} />
                          </div>
                          <div>
                            <div style={{ fontWeight: 600, fontSize: 14 }}>{p.name}</div>
                            {p.supplier && (
                              <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>{p.supplier}</div>
                            )}
                          </div>
                        </div>
                      </td>
                      <td>
                        <code className="sku-code">{p.sku || '—'}</code>
                      </td>
                      <td>
                        <span className="badge badge-info">{p.category}</span>
                      </td>
                      <td>
                        <span style={{ fontWeight: 600, color: 'var(--success)' }}>
                          ${p.price.toFixed(2)}
                        </span>
                      </td>
                      <td>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                          <span style={{ fontWeight: 700 }}>{p.quantity} <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>{p.unit}</span></span>
                          <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>Min: {p.minQuantity}</span>
                        </div>
                      </td>
                      <td>{getStockBadge(p.quantity, p.minQuantity)}</td>
                      <td>
                        <div style={{ display: 'flex', gap: 6 }}>
                          <button
                            className="btn btn-ghost btn-icon btn-sm"
                            onClick={() => { setEditProduct(p); setShowModal(true) }}
                            title={t('edit')}
                          >
                            <Edit size={14} />
                          </button>
                          {user?.isAdmin && (
                            <button
                              className="btn btn-danger btn-icon btn-sm"
                              onClick={() => setDeleteConfirm(p)}
                              title={t('delete')}
                            >
                              <Trash2 size={14} />
                            </button>
                          )}
                        </div>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>

          {/* Pagination */}
          <div className="pagination">
            <span className="pagination-info">
              {t('showing')} {Math.min((params.page - 1) * params.pageSize + 1, totalCount)}–
              {Math.min(params.page * params.pageSize, totalCount)} {t('of')} {totalCount}
            </span>
            <div className="pagination-controls">
              <button
                className="page-btn"
                disabled={params.page === 1}
                onClick={() => setParams(p => ({ ...p, page: p.page - 1 }))}
              >
                <ChevronLeft size={14} />
              </button>
              {Array.from({ length: Math.min(totalPages, 5) }, (_, i) => {
                const pg = i + 1
                return (
                  <button
                    key={pg}
                    className={`page-btn ${params.page === pg ? 'active' : ''}`}
                    onClick={() => setParams(p => ({ ...p, page: pg }))}
                  >
                    {pg}
                  </button>
                )
              })}
              <button
                className="page-btn"
                disabled={params.page === totalPages}
                onClick={() => setParams(p => ({ ...p, page: p.page + 1 }))}
              >
                <ChevronRight size={14} />
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Grid View */}
      {viewMode === 'grid' && (
        <div className="products-grid">
          {isLoading
            ? Array.from({ length: 8 }).map((_, i) => (
                <div key={i} className="skeleton" style={{ height: 180, borderRadius: 12 }} />
              ))
            : products.map((p: any) => (
                <div key={p.id} className="product-card">
                  <div className="product-card-header">
                    <div className="product-card-icon">
                      <Package size={20} />
                    </div>
                    {getStockBadge(p.quantity, p.minQuantity)}
                  </div>
                  <h3 className="product-card-name">{p.name}</h3>
                  <p className="product-card-sku">{p.sku}</p>
                  <div className="product-card-stats">
                    <div>
                      <span className="product-card-price">${p.price.toFixed(2)}</span>
                      <span className="product-card-unit">/ {p.unit}</span>
                    </div>
                    <span className="badge badge-info">{p.category}</span>
                  </div>
                  <div className="product-card-qty">
                    <span>Qty: <strong>{p.quantity}</strong></span>
                    <span className="text-muted">Min: {p.minQuantity}</span>
                  </div>
                  <div className="product-card-actions">
                    <button
                      className="btn btn-ghost btn-sm"
                      onClick={() => { setEditProduct(p); setShowModal(true) }}
                    >
                      <Edit size={13} /> {t('edit')}
                    </button>
                    {user?.isAdmin && (
                      <button
                        className="btn btn-danger btn-sm"
                        onClick={() => setDeleteConfirm(p)}
                      >
                        <Trash2 size={13} /> {t('delete')}
                      </button>
                    )}
                  </div>
                </div>
              ))
          }
        </div>
      )}

      {/* Product Modal */}
      {showModal && (
        <ProductModal
          product={editProduct}
          onClose={() => setShowModal(false)}
        />
      )}

      {/* Delete Confirm Modal */}
      {deleteConfirm && (
        <div className="modal-overlay" onClick={() => setDeleteConfirm(null)}>
          <div className="modal" style={{ maxWidth: 400 }} onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h3 className="modal-title" style={{ color: 'var(--danger)' }}>
                <Trash2 size={18} style={{ display: 'inline', marginRight: 8 }} />
                {t('deleteProduct')}
              </h3>
            </div>
            <div className="modal-body">
              <p style={{ color: 'var(--text-secondary)', fontSize: 14 }}>
                {t('confirmDelete')}
              </p>
              <p style={{ marginTop: 8, fontWeight: 600, color: 'var(--text-primary)' }}>
                "{deleteConfirm.name}"
              </p>
            </div>
            <div className="modal-footer">
              <button className="btn btn-ghost" onClick={() => setDeleteConfirm(null)}>
                {t('cancel')}
              </button>
              <button
                className="btn btn-danger"
                onClick={() => deleteMutation.mutate(deleteConfirm.id)}
                disabled={deleteMutation.isPending}
              >
                {deleteMutation.isPending ? <span className="spinner" /> : <Trash2 size={14} />}
                {t('delete')}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
